# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Alex Hewitt's Blog
site_description: Alex Hewitt's personal blog.
site_url: https://blog.alexjhewitt.com

theme:
  name: material
plugins:
  - search
  - blog
